In [ ]:
import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
import numpy as np

In [4]:
homepage_action  = pd.read_csv(r'homepage_actions.csv')
homepage_action.head()

                    timestamp      id       group action
0  2016-09-24 17:42:27.839496  804196  experiment   view
1  2016-09-24 19:19:03.542569  434745  experiment   view
2  2016-09-24 19:36:00.944135  507599  experiment   view
3  2016-09-24 19:59:02.646620  671993     control   view
4  2016-09-24 20:26:14.466886  536734  experiment   view

In [12]:
experimental_group = homepage_action[homepage_action['group'] == "experiment"]
experimental_group.head()

                    timestamp      id       group action
0  2016-09-24 17:42:27.839496  804196  experiment   view
1  2016-09-24 19:19:03.542569  434745  experiment   view
2  2016-09-24 19:36:00.944135  507599  experiment   view
4  2016-09-24 20:26:14.466886  536734  experiment   view
5  2016-09-24 20:32:25.712659  681598  experiment   view

In [8]:
click_action = experimental_group['action'].value_counts()
click_action

action
view     2996
click     928
Name: count, dtype: int64

In [14]:
control_group = homepage_action[homepage_action['group'] == "control"]
control_group.head()

                     timestamp      id    group action
3   2016-09-24 19:59:02.646620  671993  control   view
9   2016-09-24 21:00:12.278374  560027  control   view
23  2016-09-25 00:25:14.141290  281985  control   view
24  2016-09-25 01:14:48.603202  407864  control   view
25  2016-09-25 02:16:11.046654  342984  control   view

In [15]:
click_action_control = control_group['action'].value_counts()
click_action_control

action
view     3332
click     932
Name: count, dtype: int64

In [16]:
experimental_views = (experimental_group["action"] == "view").sum()
experimental_views

np.int64(2996)

In [18]:
experimental_clicks = (experimental_group["action"] == "click").sum()
experimental_clicks

np.int64(928)

In [19]:
experimental_ctr = (experimental_clicks / experimental_views)
experimental_ctr

np.float64(0.3097463284379172)

In [20]:
control_views = (control_group["action"] == "view").sum()
control_views

np.int64(3332)

In [21]:
control_clicks = (control_group["action"] == "click").sum()
control_clicks

np.int64(932)

In [22]:
control_ctr = (control_clicks / control_views)
control_ctr

np.float64(0.2797118847539016)

In [29]:
e_sum = experimental_group["action"].value_counts()
e_sum

action
view     2996
click     928
Name: count, dtype: int64

In [30]:
experimental_mean = (experimental_views*experimental_ctr)
experimental_mean

np.float64(928.0)

In [31]:
control_mean = (control_views*control_ctr)
control_mean

np.float64(932.0)

In [ ]:
# compute two-sided p-value for difference in proportions (CTR)
p1 = experimental_ctr
p2 = control_ctr
n1 = experimental_views
n2 = control_views

if n1 == 0 or n2 == 0:
	raise ValueError("One of the groups has zero views; cannot compute p-value.")

# pooled proportion
p_pool = (experimental_clicks + control_clicks) / (n1 + n2)

# standard error for difference in proportions
se = np.sqrt(p_pool * (1 - p_pool) * (1/n1 + 1/n2))

# z-statistic
z = (p1 - p2) / se

# two-sided p-value
p_value = 2 * (1 - stats.norm.cdf(abs(z)))
p_value

NameError: name 'cdf' is not defined